steps:
  - label: "mint-oidc"
    agents:
      queue: local
    command: |
      buildkite-agent oidc request-token --audience anything > oidc.txt
      echo "--- TOKEN BELOW ---"
      cat oidc.txt
